import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, Compass, Spark } from "../ui/icons";

export const metadata: Metadata = { title: "Advancement", description: "Advisory and partnership for leaders, teams, and organizations moving forward." };

export default function AdvancementPage() {
  return <>
    <section className="adv-hero"><div className="shell"><p className="eyebrow light"><span/> Advancement</p><h1>Moving forward,<br/><em>on purpose.</em></h1><p>Focused support for leaders and teams at an inflection point—when the old way has run its course and the next one needs shaping.</p><Link href="/contact" className="button button-coral">Explore a partnership <ArrowUpRight/></Link></div><div className="adv-rings"><span/><span/><span/></div></section>
    <section className="shell advancement-intro"><div><p className="eyebrow"><span/> When to reach out</p><h2>Change is already happening.<br/>The question is how you meet it.</h2></div><p>You might be entering a new market, reshaping a portfolio, bringing teams together, or stepping into a bigger leadership mandate. I help you slow down the right questions so you can move faster on the answers.</p></section>
    <section className="shell offer-grid"><article><span className="offer-icon"><Compass/></span><p className="eyebrow"><span/> For organizations</p><h3>Strategic partnership</h3><p>Embedded, senior-level support to frame the challenge, align decision-makers, and mobilize the work.</p><ul><li>Strategic narrative and choices</li><li>Portfolio and proposition direction</li><li>Operating model and team alignment</li></ul><Link href="/contact" className="text-link">Discuss an engagement <ArrowUpRight/></Link></article><article><span className="offer-icon coral"><Spark/></span><p className="eyebrow"><span/> For leaders</p><h3>Leadership advisory</h3><p>A clear-thinking partnership for leaders navigating complexity, transition, or a meaningful stretch.</p><ul><li>Decision and priority clarity</li><li>Leadership narrative and influence</li><li>90-day transition support</li></ul><Link href="/contact" className="text-link">Explore advisory <ArrowUpRight/></Link></article></section>
    <section className="process-section"><div className="shell"><div className="section-heading"><div><p className="eyebrow light"><span/> The approach</p><h2>Rigorous enough to<br/>create confidence.<br/><em>Human enough to work.</em></h2></div><p>No theater, no off-the-shelf transformation. We build only what the work needs.</p></div><div className="process-grid"><article><span>01</span><h3>See the system</h3><p>Listen widely, surface patterns, and frame the real challenge beneath the presenting one.</p></article><article><span>02</span><h3>Make the choices</h3><p>Build conviction around a focused direction and the tradeoffs it requires.</p></article><article><span>03</span><h3>Create movement</h3><p>Translate direction into ownership, practical action, and visible early progress.</p></article><article><span>04</span><h3>Leave capability</h3><p>Strengthen the people and systems that will carry the work forward without me.</p></article></div></div></section>
    <section className="shell quote-block"><blockquote>“Avery brought the rare combination of altitude and empathy. We left with a better strategy—and a stronger team.”</blockquote><p><strong>Chief Product Officer</strong><br/>Global technology organization</p></section>
  </>;
}
